# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rock_paper_scissors-tf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rock_paper_scissors-tf
    pod 'TensorFlowLiteSwift'

  target 'rock_paper_scissors-tfTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'TensorFlowLiteSwift'
  end

end
